# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "33a5c7d59030db5a138dc1268dec6363"
name = "MSC-APP"
handle = "msc-app-2"
application_url = "https://commented-dumb-listed-lawsuit.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1a6fdca7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://commented-dumb-listed-lawsuit.trycloudflare.com/auth/callback",
  "https://commented-dumb-listed-lawsuit.trycloudflare.com/auth/shopify/callback",
  "https://commented-dumb-listed-lawsuit.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
